---
###
- hosts: keeper
  gather_facts: no
  remote_user: root
###
  vars_files:
    - Vars/Group2/Group2_keeper.yml

  tasks:
    - name: stop node
      shell:
        MEFS_PATH={{ node_root }}/.{{ node_release }} {{ node_root }}/{{ node_release }} daemon stop
